
const Blog = ({requiredFullHeight}) => {
  return (
    <div className={`${requiredFullHeight && 'min-h-100vh'} blog wrapper`}>
      <h2 className="feature-title blog">Bolg</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim fugit architecto alias ipsa nobis id eveniet? Aut nesciunt quod dolorum velit nulla expedita? Sunt maxime nostrum illum ipsum. Molestiae voluptas error debitis unde? Commodi ex quas facere atque at voluptatem autem provident tenetur totam ullam, voluptatibus eaque, delectus, sapiente explicabo itaque officia blanditiis quae unde hic reprehenderit voluptatum saepe! Odio quam saepe voluptatum maxime, praesentium tenetur qui distinctio? Quasi est vero repudiandae ipsam natus, asperiores temporibus eveniet ab nisi dolore non repellendus error quam ex eos odit rem ducimus soluta eum dolorum id fuga. Iste labore veritatis quasi impedit in hic! Totam at voluptatibus asperiores, dolorem, quam doloribus optio dolore modi aspernatur esse, excepturi quo fugiat ducimus. Quae autem nam, laboriosam, natus odit ipsam illo minima, amet doloremque ut eum dolore sequi reprehenderit sed aperiam nobis voluptate soluta. Unde dolor iusto quidem odio sunt, quas fugit. Libero, consequatur, tempore hic velit officia maxime quidem quod aut fugiat voluptate nulla beatae consequuntur. Deserunt aliquam, aperiam ducimus accusantium nostrum quae, commodi corporis maiores quaerat adipisci qui eius dolor velit perferendis, eveniet est illo blanditiis voluptas nihil nesciunt nam. Quos molestiae beatae pariatur praesentium iste optio unde id. Labore officia natus tempore ipsa.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, impedit. Earum, quae fugiat! Officiis adipisci aperiam consequatur fuga aspernatur explicabo, quae beatae numquam, cumque tempore nihil quaerat tenetur reprehenderit, quibusdam magnam minus blanditiis eligendi labore necessitatibus quo obcaecati suscipit? Sit natus facere perferendis voluptatibus nulla quasi fuga fugiat quisquam odit cum obcaecati et odio incidunt, sint explicabo minima facilis! Illo assumenda tempore delectus tenetur, rem in veritatis itaque vel repudiandae, at nulla magni mollitia necessitatibus labore temporibus maxime? Nostrum cumque suscipit earum reprehenderit eligendi voluptas sed est aut laboriosam harum obcaecati eos praesentium, molestiae voluptates! Tenetur eligendi cupiditate ipsum ea sint earum, enim perferendis provident, fuga nostrum ab labore aliquam totam repudiandae vel blanditiis debitis quas voluptatem facilis. Illo, odit nostrum. Iure eaque pariatur accusamus impedit aspernatur, magni ea quas maxime? Dolore expedita in consectetur asperiores cum. Id dolore debitis, eaque ab aspernatur, aut, minima a nam pariatur totam odio deleniti magnam corrupti possimus quas tempore! Ex inventore commodi officiis alias quasi, error molestias aliquid placeat sunt repudiandae, nemo culpa vitae deserunt expedita ut nam eveniet quam aliquam vel nostrum dignissimos accusantium eum mollitia? Ullam culpa eligendi consectetur modi, et, esse saepe natus officia sequi a adipisci, tempora asperiores iusto!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, impedit. Earum, quae fugiat! Officiis adipisci aperiam consequatur fuga aspernatur explicabo, quae beatae numquam, cumque tempore nihil quaerat tenetur reprehenderit, quibusdam magnam minus blanditiis eligendi labore necessitatibus quo obcaecati suscipit? Sit natus facere perferendis voluptatibus nulla quasi fuga fugiat quisquam odit cum obcaecati et odio incidunt, sint explicabo minima facilis! Illo assumenda tempore delectus tenetur, rem in veritatis itaque vel repudiandae, at nulla magni mollitia necessitatibus labore temporibus maxime? Nostrum cumque suscipit earum reprehenderit eligendi voluptas sed est aut laboriosam harum obcaecati eos praesentium, molestiae voluptates! Tenetur eligendi cupiditate ipsum ea sint earum, enim perferendis provident, fuga nostrum ab labore aliquam totam repudiandae vel blanditiis debitis quas voluptatem facilis. Illo, odit nostrum. Iure eaque pariatur accusamus impedit aspernatur, magni ea quas maxime? Dolore expedita in consectetur asperiores cum. Id dolore debitis, eaque ab aspernatur, aut, minima a nam pariatur totam odio deleniti magnam corrupti possimus quas tempore! Ex inventore commodi officiis alias quasi, error molestias aliquid placeat sunt repudiandae, nemo culpa vitae deserunt expedita ut nam eveniet quam aliquam vel nostrum dignissimos accusantium eum mollitia? Ullam culpa eligendi consectetur modi, et, esse saepe natus officia sequi a adipisci, tempora asperiores iusto!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, impedit. Earum, quae fugiat! Officiis adipisci aperiam consequatur fuga aspernatur explicabo, quae beatae numquam, cumque tempore nihil quaerat tenetur reprehenderit, quibusdam magnam minus blanditiis eligendi labore necessitatibus quo obcaecati suscipit? Sit natus facere perferendis voluptatibus nulla quasi fuga fugiat quisquam odit cum obcaecati et odio incidunt, sint explicabo minima facilis! Illo assumenda tempore delectus tenetur, rem in veritatis itaque vel repudiandae, at nulla magni mollitia necessitatibus labore temporibus maxime? Nostrum cumque suscipit earum reprehenderit eligendi voluptas sed est aut laboriosam harum obcaecati eos praesentium, molestiae voluptates! Tenetur eligendi cupiditate ipsum ea sint earum, enim perferendis provident, fuga nostrum ab labore aliquam totam repudiandae vel blanditiis debitis quas voluptatem facilis. Illo, odit nostrum. Iure eaque pariatur accusamus impedit aspernatur, magni ea quas maxime? Dolore expedita in consectetur asperiores cum. Id dolore debitis, eaque ab aspernatur, aut, minima a nam pariatur totam odio deleniti magnam corrupti possimus quas tempore! Ex inventore commodi officiis alias quasi, error molestias aliquid placeat sunt repudiandae, nemo culpa vitae deserunt expedita ut nam eveniet quam aliquam vel nostrum dignissimos accusantium eum mollitia? Ullam culpa eligendi consectetur modi, et, esse saepe natus officia sequi a adipisci, tempora asperiores iusto!</p>
    </div>
  )
}

export default Blog